/** Declaration file generated by dts-gen */
import * as React from "react";
import * as Immutable from "immutable";

export type InitialState = {
  fields: Immutable.Map;
};

export type Values = {[key: string]: any};

export type Validation = (value: any, otherValues?: Values) => (string | null);

export type Action = {
  type: string;
  form: string;
  field?: string;
  property?: string;
  value?: any;
  values?: Values;
};

export interface FieldProps {
  component: Object;
  name: String | string;
}

export class Field extends React.Component<FieldProps, any> {
}

export interface ErrorCallbackObject {
  name: string;
  errors: {[key: string]: any};
}

export interface SubmitCallbackObject {
  name: string;
  values: {[key: string]: any};
}

export interface FormProps {
  method?: "POST" | "GET" | "PUT" | "DELETE";
  name: String | string;
  onError?: (e: ErrorCallbackObject) => void;
  onSubmit?: (s: SubmitCallbackObject) => void;
  validations?: {[key: string]: Validation[]};
}

declare class Form extends React.Component<FormProps, any> {
  constructor(...args: any[]);

  static defaultProps: {
    method: string;
    validations: {[key: string]: Validation[]};
  };
}

export interface SubmitProps {
  disabled: boolean;
  onClick: () => void;
}

declare class Submit extends React.Component<SubmitProps, any> {
}

export function connectField(fieldName: string, defaultProps?: Values, customValidations?: Validation[]): any;

export function connectSubmit(Submit: any): any;

export function extractPropertyFromFields(fields: any, property: string): any;

export function extractPropertyFromState(state: any, formName: any, property: string): any;

export function reducer(state: InitialState, action: Action): InitialState;

export function validateField(value: any, validations: Validation[], otherValues: Values): any;

export namespace actions {
    const CLEAR_ONION_FORM_PROPERTY: string;

    const SET_ONION_FORM_FIELD_PROPERTY: string;

    const SET_ONION_FORM_MULTIPLE_FIELDS: string;

    function clearFormProperty(form: string, property: string): Action;

    function setFieldApiError(form: string, field: string, error: string | null): Action;

    function setFieldError(form: string, field: string, error: string | null): Action;

    function setFieldLiveValidation(form: string, field: boolean): Action;

    function setFieldValue(form: string, field: string, value: any): Action;

    function setFormFieldProperty(form: string, field: string, property: string, value: any): Action;

    function setMultipleFields(form: string, property: string, values: Values): Action;

}

