// flow-typed signature: 3d0965904c165c0abc8a4505e15d1c44
// flow-typed version: <<STUB>>/babel-preset-es2015-loose_v^7.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-loose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-loose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-loose/index' {
  declare module.exports: $Exports<'babel-preset-es2015-loose'>;
}
declare module 'babel-preset-es2015-loose/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-loose'>;
}
