// flow-typed signature: d49fe7935a5d6d35a0a968e76c495b21
// flow-typed version: <<STUB>>/chai-spies_v^0.7.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-spies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-spies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-spies/chai-spies' {
  declare module.exports: any;
}

declare module 'chai-spies/lib/spy' {
  declare module.exports: any;
}

declare module 'chai-spies/support/compile' {
  declare module.exports: any;
}

declare module 'chai-spies/test/spies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-spies/chai-spies.js' {
  declare module.exports: $Exports<'chai-spies/chai-spies'>;
}
declare module 'chai-spies/index' {
  declare module.exports: $Exports<'chai-spies'>;
}
declare module 'chai-spies/index.js' {
  declare module.exports: $Exports<'chai-spies'>;
}
declare module 'chai-spies/lib/spy.js' {
  declare module.exports: $Exports<'chai-spies/lib/spy'>;
}
declare module 'chai-spies/support/compile.js' {
  declare module.exports: $Exports<'chai-spies/support/compile'>;
}
declare module 'chai-spies/test/spies.js' {
  declare module.exports: $Exports<'chai-spies/test/spies'>;
}
