// flow-typed signature: c0d943c1d6f0589e5c6eedecf3c69f12
// flow-typed version: <<STUB>>/eslint-plugin-require-jsdoc_v^1.0.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-require-jsdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-require-jsdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-require-jsdoc/lib/rules/require-jsdoc' {
  declare module.exports: any;
}

declare module 'eslint-plugin-require-jsdoc/Makefile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-require-jsdoc/index' {
  declare module.exports: $Exports<'eslint-plugin-require-jsdoc'>;
}
declare module 'eslint-plugin-require-jsdoc/index.js' {
  declare module.exports: $Exports<'eslint-plugin-require-jsdoc'>;
}
declare module 'eslint-plugin-require-jsdoc/lib/rules/require-jsdoc.js' {
  declare module.exports: $Exports<'eslint-plugin-require-jsdoc/lib/rules/require-jsdoc'>;
}
declare module 'eslint-plugin-require-jsdoc/Makefile.js' {
  declare module.exports: $Exports<'eslint-plugin-require-jsdoc/Makefile'>;
}
