// flow-typed signature: 62550e743d59e675cb6b9fdf34f172cf
// flow-typed version: <<STUB>>/eslint-plugin-jsdoc_v^3.7.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jsdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jsdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jsdoc/bin/readme-assertions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/iterateJsdoc' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/jsdocUtils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkParamNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkTagNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/newlineAfterDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/noUndefinedTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireDescriptionCompleteSentence' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireExample' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireHyphenBeforeParamDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireParam' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireParamDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireParamName' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireParamType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/validTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/tagNames' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jsdoc/bin/readme-assertions.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/bin/readme-assertions'>;
}
declare module 'eslint-plugin-jsdoc/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/index'>;
}
declare module 'eslint-plugin-jsdoc/dist/iterateJsdoc.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/iterateJsdoc'>;
}
declare module 'eslint-plugin-jsdoc/dist/jsdocUtils.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/jsdocUtils'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkParamNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkParamNames'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkTagNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkTagNames'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkTypes'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/newlineAfterDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/newlineAfterDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/noUndefinedTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/noUndefinedTypes'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireDescriptionCompleteSentence.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireDescriptionCompleteSentence'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireExample.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireExample'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireHyphenBeforeParamDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireHyphenBeforeParamDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireParam.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireParam'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireParamDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireParamDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireParamName.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireParamName'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireParamType.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireParamType'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireReturnsDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsType.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireReturnsType'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/validTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/validTypes'>;
}
declare module 'eslint-plugin-jsdoc/dist/tagNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/tagNames'>;
}
