// flow-typed signature: 6d92397cd79d214f170cf98f75e5e088
// flow-typed version: <<STUB>>/eslint-config-airbnb_v^6.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-airbnb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-airbnb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-airbnb/base' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/variables' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/test/test-base' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/test/test-react-order' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-airbnb/base.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/base'>;
}
declare module 'eslint-config-airbnb/index' {
  declare module.exports: $Exports<'eslint-config-airbnb'>;
}
declare module 'eslint-config-airbnb/index.js' {
  declare module.exports: $Exports<'eslint-config-airbnb'>;
}
declare module 'eslint-config-airbnb/legacy.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/legacy'>;
}
declare module 'eslint-config-airbnb/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/best-practices'>;
}
declare module 'eslint-config-airbnb/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/errors'>;
}
declare module 'eslint-config-airbnb/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/es6'>;
}
declare module 'eslint-config-airbnb/rules/legacy.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/legacy'>;
}
declare module 'eslint-config-airbnb/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/node'>;
}
declare module 'eslint-config-airbnb/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/react'>;
}
declare module 'eslint-config-airbnb/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/strict'>;
}
declare module 'eslint-config-airbnb/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/style'>;
}
declare module 'eslint-config-airbnb/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/variables'>;
}
declare module 'eslint-config-airbnb/test/test-base.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/test/test-base'>;
}
declare module 'eslint-config-airbnb/test/test-react-order.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/test/test-react-order'>;
}
