// flow-typed signature: 95fb23fed9d4e835303f656a1844052e
// flow-typed version: <<STUB>>/jsdoc_vgit+https://github.com/jsdoc3/jsdoc.git/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdoc/cli' {
  declare module.exports: any;
}

declare module 'jsdoc/gulpfile' {
  declare module.exports: any;
}

declare module 'jsdoc/jsdoc' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/app' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/augment' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/borrow' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/config' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/doclet' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/env' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/fs' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/name' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/opts/argparser' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/opts/args' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/package' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/path' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/plugins' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/readme' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/schema' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/astbuilder' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/astnode' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/filter' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/handlers' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/parser' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/scanner' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/syntax' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/visitor' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/walker' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/dictionary' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/dictionary/definitions' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/inline' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/type' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/validator' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/template' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tutorial' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tutorial/resolver' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/cast' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/doop' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/dumper' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/error' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/logger' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/markdown' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/runtime' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/templateHelper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/commentConvert' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/commentsOnly' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/escapeHtml' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/eventDumper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/markdown' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/overloadHelper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/partial' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/railsTemplate' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/shout' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/sourcetag' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/summarize' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/fixtures/markdown' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/fixtures/overloadHelper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/fixtures/underscore' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/commentConvert' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/escapeHtml' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/markdown' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/overloadHelper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/railsTemplate' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/shout' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/sourcetag' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/summarize' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/underscore' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/underscore' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/default/publish' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/default/static/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/default/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/default/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/haruki/publish' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/silent/publish' {
  declare module.exports: any;
}

declare module 'jsdoc/test/async-callback' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/abstracttag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/accesstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/alias' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/alias2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/alias3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/alias4' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/aliasglobal' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/aliasglobal2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/aliasresolve' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/aliasresolve2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/also' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/also2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/anonymousclass' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/arrowfunction' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/augmentall' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/augmentall2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/augmentstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/augmentstag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/augmentstag3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/augmentstag4' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/augmentstag5' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/augmentstag6' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/authortag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/borrowstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/borrowstag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/borrowstag3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/callbacktag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/classdesctag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/classtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/classtag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/classwithoutname' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/constanttag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/constanttag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/constructortag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/constructstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/constructstag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/constructstag3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/constructstag4' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/constructstag5' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/copyrighttag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/defaultparams' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/defaultparams2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/defaulttag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/deprecatedtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/descriptiontag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/destructuring' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/doclet' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/emptycomments' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/enumtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/enumtag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/es6' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/eventfirestag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/eventorder' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exampletag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exceptiontag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportclass' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportdefault' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportdefaultclass' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exports' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportstag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportstag3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportstag4' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportstag5' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportstag6' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportstag7' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/exportstag8' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/externaltag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/externaltag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/externaltag3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/file' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/funcExpression' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/funcExpression2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/funcExpression3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/functiontag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/getset' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/getset2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/globaltag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/ignoretag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/ignoretag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/inheritdoctag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/inlinecomment' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/inlineparamcomment' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/inlineparamcomment2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/inner' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/innerscope' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/innerscope2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/instanceproperty' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/interface-implements' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/interfacetag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/jsx' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/kindtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/lends' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/lends2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/lends3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/lends4' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/lends5' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/lends6' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/lendsglobal' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/letkeyword' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/licensetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/linktag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/listenstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/memberoftag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/memberoftag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/memberoftag3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/memberoftag4' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/memberoftag5' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/memberoftagforced' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/membertag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/methoddefinition' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/mixintag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/mixintag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduleinner' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduleisconstructor' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduleisconstructor2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduleisfunction' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/modules/data/mod-1' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/modules/data/mod-2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/modules/data/mod-3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag10' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag4' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag5' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag6' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag7' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag8' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/moduletag9' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/namespacetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/nametag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/numericpropertytag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/objectkeys' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/objectlit' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/objectlit2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/objectlit3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/objectpropertykeys' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/overridetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/paramtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/paramtag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/paramtaginvalidtype' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/plugins' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/privatetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/privatetag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/projecttag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/propertytag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/protectedtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/protectedtag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/quotename' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/quotename2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/readonlytag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/requirestag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/restparams' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/restparams2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/returnstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/scopetags' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/seetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/sincetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/specialchars' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/specialnames' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/src/_dir2/four' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/src/_ignored' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/src/dir1/three' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/src/one' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/src/two' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/starbangstar' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/summarytag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/testPlugin1' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/testPlugin2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/this-and-objectlit' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/this' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/this2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/this3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/this4' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/this5' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/thistag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/todotag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/tutorialtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/typedeftag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/typekind' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/typetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/typetag2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/typetaginline' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/typetagwithnewline' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/undocumentedtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/utf8' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/var' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/variations' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/variationtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/versiontag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/virtual' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/virtual2' {
  declare module.exports: any;
}

declare module 'jsdoc/test/fixtures/virtual3' {
  declare module.exports: any;
}

declare module 'jsdoc/test/jasmine-jsdoc' {
  declare module.exports: any;
}

declare module 'jsdoc/test/lib/jasmine' {
  declare module.exports: any;
}

declare module 'jsdoc/test/reporter' {
  declare module.exports: any;
}

declare module 'jsdoc/test/runner' {
  declare module.exports: any;
}

declare module 'jsdoc/test/spec-collection' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/alias' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/also' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/anonymousclass' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/arrowfunction' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/callback' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/classwithoutname' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/const' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/defaultparams' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/emptycomments' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/exportclass' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/exportdefault' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/exportdefaultclass' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/exports' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/funcExpression' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/getset' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/inlinecomment' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/inlineparamcomment' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/inner' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/innerscope' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/instanceproperty' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/jsx' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/lends' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/letkeyword' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/methoddefinition' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/mixins' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/moduleinner' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/moduleisconstructor' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/moduleisfunction' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/modules' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/objectkeys' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/objectlit' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/objectpropertykeys' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/quotename' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/restparams' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/specialchars' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/specialnames' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/starbangstar' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/this' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/typetaginline' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/typetagwithnewline' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/var' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/variations' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/documentation/virtual' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/augment' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/borrow' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/config' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/doclet' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/name' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/opts/argparser' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/opts/args' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/package' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/path' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/plugins' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/readme' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/schema' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/src/astbuilder' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/src/astnode' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/src/filter' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/src/handlers' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/src/parser' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/src/scanner' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/src/syntax' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/src/visitor' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/src/walker' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/tag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/tag/dictionary' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/tag/dictionary/definitions' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/tag/inline' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/tag/type' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/tag/validator' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/template' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/tutorial' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/tutorial/resolver' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/util/cast' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/util/doop' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/util/dumper' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/util/error' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/util/logger' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/util/markdown' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/util/runtime' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/jsdoc/util/templateHelper' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/plugins/plugins' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/abstracttag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/accesstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/aliastag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/augmentstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/authortag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/borrowstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/classdesctag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/classtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/constanttag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/constructortag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/constructstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/copyrighttag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/defaulttag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/deprecatedtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/descriptiontag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/enumtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/eventfirestag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/exampletag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/exceptiontag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/exportstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/externaltag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/functiontag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/globaltag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/ignoretag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/implementstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/inheritdoctag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/interfacetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/kindtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/lendstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/licensetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/listenstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/memberoftag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/membertag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/mixestag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/mixintag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/moduletag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/namespacetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/nametag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/overridetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/overviewtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/paramtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/privatetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/propertytag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/protectedtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/readonlytag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/requirestag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/returnstag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/scopetags' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/seetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/sincetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/summarytag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/thistag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/todotag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/tutorialtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/typedeftag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/typekind' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/typetag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/undocumentedtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/variationtag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/specs/tags/versiontag' {
  declare module.exports: any;
}

declare module 'jsdoc/test/tutorials/src/x' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdoc/cli.js' {
  declare module.exports: $Exports<'jsdoc/cli'>;
}
declare module 'jsdoc/gulpfile.js' {
  declare module.exports: $Exports<'jsdoc/gulpfile'>;
}
declare module 'jsdoc/jsdoc.js' {
  declare module.exports: $Exports<'jsdoc/jsdoc'>;
}
declare module 'jsdoc/lib/jsdoc/app.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/app'>;
}
declare module 'jsdoc/lib/jsdoc/augment.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/augment'>;
}
declare module 'jsdoc/lib/jsdoc/borrow.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/borrow'>;
}
declare module 'jsdoc/lib/jsdoc/config.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/config'>;
}
declare module 'jsdoc/lib/jsdoc/doclet.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/doclet'>;
}
declare module 'jsdoc/lib/jsdoc/env.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/env'>;
}
declare module 'jsdoc/lib/jsdoc/fs.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/fs'>;
}
declare module 'jsdoc/lib/jsdoc/name.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/name'>;
}
declare module 'jsdoc/lib/jsdoc/opts/argparser.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/opts/argparser'>;
}
declare module 'jsdoc/lib/jsdoc/opts/args.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/opts/args'>;
}
declare module 'jsdoc/lib/jsdoc/package.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/package'>;
}
declare module 'jsdoc/lib/jsdoc/path.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/path'>;
}
declare module 'jsdoc/lib/jsdoc/plugins.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/plugins'>;
}
declare module 'jsdoc/lib/jsdoc/readme.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/readme'>;
}
declare module 'jsdoc/lib/jsdoc/schema.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/schema'>;
}
declare module 'jsdoc/lib/jsdoc/src/astbuilder.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/astbuilder'>;
}
declare module 'jsdoc/lib/jsdoc/src/astnode.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/astnode'>;
}
declare module 'jsdoc/lib/jsdoc/src/filter.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/filter'>;
}
declare module 'jsdoc/lib/jsdoc/src/handlers.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/handlers'>;
}
declare module 'jsdoc/lib/jsdoc/src/parser.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/parser'>;
}
declare module 'jsdoc/lib/jsdoc/src/scanner.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/scanner'>;
}
declare module 'jsdoc/lib/jsdoc/src/syntax.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/syntax'>;
}
declare module 'jsdoc/lib/jsdoc/src/visitor.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/visitor'>;
}
declare module 'jsdoc/lib/jsdoc/src/walker.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/walker'>;
}
declare module 'jsdoc/lib/jsdoc/tag.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag'>;
}
declare module 'jsdoc/lib/jsdoc/tag/dictionary.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/dictionary'>;
}
declare module 'jsdoc/lib/jsdoc/tag/dictionary/definitions.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/dictionary/definitions'>;
}
declare module 'jsdoc/lib/jsdoc/tag/inline.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/inline'>;
}
declare module 'jsdoc/lib/jsdoc/tag/type.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/type'>;
}
declare module 'jsdoc/lib/jsdoc/tag/validator.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/validator'>;
}
declare module 'jsdoc/lib/jsdoc/template.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/template'>;
}
declare module 'jsdoc/lib/jsdoc/tutorial.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tutorial'>;
}
declare module 'jsdoc/lib/jsdoc/tutorial/resolver.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tutorial/resolver'>;
}
declare module 'jsdoc/lib/jsdoc/util/cast.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/cast'>;
}
declare module 'jsdoc/lib/jsdoc/util/doop.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/doop'>;
}
declare module 'jsdoc/lib/jsdoc/util/dumper.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/dumper'>;
}
declare module 'jsdoc/lib/jsdoc/util/error.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/error'>;
}
declare module 'jsdoc/lib/jsdoc/util/logger.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/logger'>;
}
declare module 'jsdoc/lib/jsdoc/util/markdown.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/markdown'>;
}
declare module 'jsdoc/lib/jsdoc/util/runtime.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/runtime'>;
}
declare module 'jsdoc/lib/jsdoc/util/templateHelper.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/templateHelper'>;
}
declare module 'jsdoc/plugins/commentConvert.js' {
  declare module.exports: $Exports<'jsdoc/plugins/commentConvert'>;
}
declare module 'jsdoc/plugins/commentsOnly.js' {
  declare module.exports: $Exports<'jsdoc/plugins/commentsOnly'>;
}
declare module 'jsdoc/plugins/escapeHtml.js' {
  declare module.exports: $Exports<'jsdoc/plugins/escapeHtml'>;
}
declare module 'jsdoc/plugins/eventDumper.js' {
  declare module.exports: $Exports<'jsdoc/plugins/eventDumper'>;
}
declare module 'jsdoc/plugins/markdown.js' {
  declare module.exports: $Exports<'jsdoc/plugins/markdown'>;
}
declare module 'jsdoc/plugins/overloadHelper.js' {
  declare module.exports: $Exports<'jsdoc/plugins/overloadHelper'>;
}
declare module 'jsdoc/plugins/partial.js' {
  declare module.exports: $Exports<'jsdoc/plugins/partial'>;
}
declare module 'jsdoc/plugins/railsTemplate.js' {
  declare module.exports: $Exports<'jsdoc/plugins/railsTemplate'>;
}
declare module 'jsdoc/plugins/shout.js' {
  declare module.exports: $Exports<'jsdoc/plugins/shout'>;
}
declare module 'jsdoc/plugins/sourcetag.js' {
  declare module.exports: $Exports<'jsdoc/plugins/sourcetag'>;
}
declare module 'jsdoc/plugins/summarize.js' {
  declare module.exports: $Exports<'jsdoc/plugins/summarize'>;
}
declare module 'jsdoc/plugins/test/fixtures/markdown.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/fixtures/markdown'>;
}
declare module 'jsdoc/plugins/test/fixtures/overloadHelper.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/fixtures/overloadHelper'>;
}
declare module 'jsdoc/plugins/test/fixtures/underscore.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/fixtures/underscore'>;
}
declare module 'jsdoc/plugins/test/specs/commentConvert.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/commentConvert'>;
}
declare module 'jsdoc/plugins/test/specs/escapeHtml.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/escapeHtml'>;
}
declare module 'jsdoc/plugins/test/specs/markdown.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/markdown'>;
}
declare module 'jsdoc/plugins/test/specs/overloadHelper.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/overloadHelper'>;
}
declare module 'jsdoc/plugins/test/specs/railsTemplate.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/railsTemplate'>;
}
declare module 'jsdoc/plugins/test/specs/shout.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/shout'>;
}
declare module 'jsdoc/plugins/test/specs/sourcetag.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/sourcetag'>;
}
declare module 'jsdoc/plugins/test/specs/summarize.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/summarize'>;
}
declare module 'jsdoc/plugins/test/specs/underscore.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/underscore'>;
}
declare module 'jsdoc/plugins/underscore.js' {
  declare module.exports: $Exports<'jsdoc/plugins/underscore'>;
}
declare module 'jsdoc/templates/default/publish.js' {
  declare module.exports: $Exports<'jsdoc/templates/default/publish'>;
}
declare module 'jsdoc/templates/default/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'jsdoc/templates/default/static/scripts/linenumber'>;
}
declare module 'jsdoc/templates/default/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jsdoc/templates/default/static/scripts/prettify/lang-css'>;
}
declare module 'jsdoc/templates/default/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jsdoc/templates/default/static/scripts/prettify/prettify'>;
}
declare module 'jsdoc/templates/haruki/publish.js' {
  declare module.exports: $Exports<'jsdoc/templates/haruki/publish'>;
}
declare module 'jsdoc/templates/silent/publish.js' {
  declare module.exports: $Exports<'jsdoc/templates/silent/publish'>;
}
declare module 'jsdoc/test/async-callback.js' {
  declare module.exports: $Exports<'jsdoc/test/async-callback'>;
}
declare module 'jsdoc/test/fixtures/abstracttag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/abstracttag'>;
}
declare module 'jsdoc/test/fixtures/accesstag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/accesstag'>;
}
declare module 'jsdoc/test/fixtures/alias.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/alias'>;
}
declare module 'jsdoc/test/fixtures/alias2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/alias2'>;
}
declare module 'jsdoc/test/fixtures/alias3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/alias3'>;
}
declare module 'jsdoc/test/fixtures/alias4.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/alias4'>;
}
declare module 'jsdoc/test/fixtures/aliasglobal.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/aliasglobal'>;
}
declare module 'jsdoc/test/fixtures/aliasglobal2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/aliasglobal2'>;
}
declare module 'jsdoc/test/fixtures/aliasresolve.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/aliasresolve'>;
}
declare module 'jsdoc/test/fixtures/aliasresolve2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/aliasresolve2'>;
}
declare module 'jsdoc/test/fixtures/also.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/also'>;
}
declare module 'jsdoc/test/fixtures/also2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/also2'>;
}
declare module 'jsdoc/test/fixtures/anonymousclass.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/anonymousclass'>;
}
declare module 'jsdoc/test/fixtures/arrowfunction.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/arrowfunction'>;
}
declare module 'jsdoc/test/fixtures/augmentall.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/augmentall'>;
}
declare module 'jsdoc/test/fixtures/augmentall2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/augmentall2'>;
}
declare module 'jsdoc/test/fixtures/augmentstag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/augmentstag'>;
}
declare module 'jsdoc/test/fixtures/augmentstag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/augmentstag2'>;
}
declare module 'jsdoc/test/fixtures/augmentstag3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/augmentstag3'>;
}
declare module 'jsdoc/test/fixtures/augmentstag4.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/augmentstag4'>;
}
declare module 'jsdoc/test/fixtures/augmentstag5.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/augmentstag5'>;
}
declare module 'jsdoc/test/fixtures/augmentstag6.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/augmentstag6'>;
}
declare module 'jsdoc/test/fixtures/authortag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/authortag'>;
}
declare module 'jsdoc/test/fixtures/borrowstag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/borrowstag'>;
}
declare module 'jsdoc/test/fixtures/borrowstag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/borrowstag2'>;
}
declare module 'jsdoc/test/fixtures/borrowstag3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/borrowstag3'>;
}
declare module 'jsdoc/test/fixtures/callbacktag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/callbacktag'>;
}
declare module 'jsdoc/test/fixtures/classdesctag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/classdesctag'>;
}
declare module 'jsdoc/test/fixtures/classtag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/classtag'>;
}
declare module 'jsdoc/test/fixtures/classtag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/classtag2'>;
}
declare module 'jsdoc/test/fixtures/classwithoutname.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/classwithoutname'>;
}
declare module 'jsdoc/test/fixtures/constanttag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/constanttag'>;
}
declare module 'jsdoc/test/fixtures/constanttag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/constanttag2'>;
}
declare module 'jsdoc/test/fixtures/constructortag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/constructortag'>;
}
declare module 'jsdoc/test/fixtures/constructstag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/constructstag'>;
}
declare module 'jsdoc/test/fixtures/constructstag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/constructstag2'>;
}
declare module 'jsdoc/test/fixtures/constructstag3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/constructstag3'>;
}
declare module 'jsdoc/test/fixtures/constructstag4.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/constructstag4'>;
}
declare module 'jsdoc/test/fixtures/constructstag5.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/constructstag5'>;
}
declare module 'jsdoc/test/fixtures/copyrighttag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/copyrighttag'>;
}
declare module 'jsdoc/test/fixtures/defaultparams.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/defaultparams'>;
}
declare module 'jsdoc/test/fixtures/defaultparams2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/defaultparams2'>;
}
declare module 'jsdoc/test/fixtures/defaulttag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/defaulttag'>;
}
declare module 'jsdoc/test/fixtures/deprecatedtag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/deprecatedtag'>;
}
declare module 'jsdoc/test/fixtures/descriptiontag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/descriptiontag'>;
}
declare module 'jsdoc/test/fixtures/destructuring.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/destructuring'>;
}
declare module 'jsdoc/test/fixtures/doclet.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/doclet'>;
}
declare module 'jsdoc/test/fixtures/emptycomments.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/emptycomments'>;
}
declare module 'jsdoc/test/fixtures/enumtag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/enumtag'>;
}
declare module 'jsdoc/test/fixtures/enumtag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/enumtag2'>;
}
declare module 'jsdoc/test/fixtures/es6.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/es6'>;
}
declare module 'jsdoc/test/fixtures/eventfirestag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/eventfirestag'>;
}
declare module 'jsdoc/test/fixtures/eventorder.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/eventorder'>;
}
declare module 'jsdoc/test/fixtures/exampletag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exampletag'>;
}
declare module 'jsdoc/test/fixtures/exceptiontag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exceptiontag'>;
}
declare module 'jsdoc/test/fixtures/exportclass.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportclass'>;
}
declare module 'jsdoc/test/fixtures/exportdefault.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportdefault'>;
}
declare module 'jsdoc/test/fixtures/exportdefaultclass.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportdefaultclass'>;
}
declare module 'jsdoc/test/fixtures/exports.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exports'>;
}
declare module 'jsdoc/test/fixtures/exportstag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportstag'>;
}
declare module 'jsdoc/test/fixtures/exportstag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportstag2'>;
}
declare module 'jsdoc/test/fixtures/exportstag3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportstag3'>;
}
declare module 'jsdoc/test/fixtures/exportstag4.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportstag4'>;
}
declare module 'jsdoc/test/fixtures/exportstag5.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportstag5'>;
}
declare module 'jsdoc/test/fixtures/exportstag6.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportstag6'>;
}
declare module 'jsdoc/test/fixtures/exportstag7.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportstag7'>;
}
declare module 'jsdoc/test/fixtures/exportstag8.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/exportstag8'>;
}
declare module 'jsdoc/test/fixtures/externaltag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/externaltag'>;
}
declare module 'jsdoc/test/fixtures/externaltag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/externaltag2'>;
}
declare module 'jsdoc/test/fixtures/externaltag3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/externaltag3'>;
}
declare module 'jsdoc/test/fixtures/file.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/file'>;
}
declare module 'jsdoc/test/fixtures/funcExpression.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/funcExpression'>;
}
declare module 'jsdoc/test/fixtures/funcExpression2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/funcExpression2'>;
}
declare module 'jsdoc/test/fixtures/funcExpression3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/funcExpression3'>;
}
declare module 'jsdoc/test/fixtures/functiontag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/functiontag'>;
}
declare module 'jsdoc/test/fixtures/getset.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/getset'>;
}
declare module 'jsdoc/test/fixtures/getset2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/getset2'>;
}
declare module 'jsdoc/test/fixtures/globaltag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/globaltag'>;
}
declare module 'jsdoc/test/fixtures/ignoretag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/ignoretag'>;
}
declare module 'jsdoc/test/fixtures/ignoretag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/ignoretag2'>;
}
declare module 'jsdoc/test/fixtures/inheritdoctag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/inheritdoctag'>;
}
declare module 'jsdoc/test/fixtures/inlinecomment.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/inlinecomment'>;
}
declare module 'jsdoc/test/fixtures/inlineparamcomment.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/inlineparamcomment'>;
}
declare module 'jsdoc/test/fixtures/inlineparamcomment2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/inlineparamcomment2'>;
}
declare module 'jsdoc/test/fixtures/inner.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/inner'>;
}
declare module 'jsdoc/test/fixtures/innerscope.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/innerscope'>;
}
declare module 'jsdoc/test/fixtures/innerscope2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/innerscope2'>;
}
declare module 'jsdoc/test/fixtures/instanceproperty.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/instanceproperty'>;
}
declare module 'jsdoc/test/fixtures/interface-implements.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/interface-implements'>;
}
declare module 'jsdoc/test/fixtures/interfacetag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/interfacetag2'>;
}
declare module 'jsdoc/test/fixtures/jsx.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/jsx'>;
}
declare module 'jsdoc/test/fixtures/kindtag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/kindtag'>;
}
declare module 'jsdoc/test/fixtures/lends.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/lends'>;
}
declare module 'jsdoc/test/fixtures/lends2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/lends2'>;
}
declare module 'jsdoc/test/fixtures/lends3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/lends3'>;
}
declare module 'jsdoc/test/fixtures/lends4.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/lends4'>;
}
declare module 'jsdoc/test/fixtures/lends5.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/lends5'>;
}
declare module 'jsdoc/test/fixtures/lends6.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/lends6'>;
}
declare module 'jsdoc/test/fixtures/lendsglobal.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/lendsglobal'>;
}
declare module 'jsdoc/test/fixtures/letkeyword.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/letkeyword'>;
}
declare module 'jsdoc/test/fixtures/licensetag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/licensetag'>;
}
declare module 'jsdoc/test/fixtures/linktag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/linktag'>;
}
declare module 'jsdoc/test/fixtures/listenstag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/listenstag'>;
}
declare module 'jsdoc/test/fixtures/memberoftag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/memberoftag'>;
}
declare module 'jsdoc/test/fixtures/memberoftag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/memberoftag2'>;
}
declare module 'jsdoc/test/fixtures/memberoftag3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/memberoftag3'>;
}
declare module 'jsdoc/test/fixtures/memberoftag4.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/memberoftag4'>;
}
declare module 'jsdoc/test/fixtures/memberoftag5.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/memberoftag5'>;
}
declare module 'jsdoc/test/fixtures/memberoftagforced.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/memberoftagforced'>;
}
declare module 'jsdoc/test/fixtures/membertag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/membertag'>;
}
declare module 'jsdoc/test/fixtures/methoddefinition.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/methoddefinition'>;
}
declare module 'jsdoc/test/fixtures/mixintag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/mixintag'>;
}
declare module 'jsdoc/test/fixtures/mixintag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/mixintag2'>;
}
declare module 'jsdoc/test/fixtures/moduleinner.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduleinner'>;
}
declare module 'jsdoc/test/fixtures/moduleisconstructor.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduleisconstructor'>;
}
declare module 'jsdoc/test/fixtures/moduleisconstructor2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduleisconstructor2'>;
}
declare module 'jsdoc/test/fixtures/moduleisfunction.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduleisfunction'>;
}
declare module 'jsdoc/test/fixtures/modules/data/mod-1.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/modules/data/mod-1'>;
}
declare module 'jsdoc/test/fixtures/modules/data/mod-2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/modules/data/mod-2'>;
}
declare module 'jsdoc/test/fixtures/modules/data/mod-3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/modules/data/mod-3'>;
}
declare module 'jsdoc/test/fixtures/moduletag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag'>;
}
declare module 'jsdoc/test/fixtures/moduletag10.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag10'>;
}
declare module 'jsdoc/test/fixtures/moduletag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag2'>;
}
declare module 'jsdoc/test/fixtures/moduletag3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag3'>;
}
declare module 'jsdoc/test/fixtures/moduletag4.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag4'>;
}
declare module 'jsdoc/test/fixtures/moduletag5.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag5'>;
}
declare module 'jsdoc/test/fixtures/moduletag6.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag6'>;
}
declare module 'jsdoc/test/fixtures/moduletag7.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag7'>;
}
declare module 'jsdoc/test/fixtures/moduletag8.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag8'>;
}
declare module 'jsdoc/test/fixtures/moduletag9.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/moduletag9'>;
}
declare module 'jsdoc/test/fixtures/namespacetag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/namespacetag'>;
}
declare module 'jsdoc/test/fixtures/nametag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/nametag'>;
}
declare module 'jsdoc/test/fixtures/numericpropertytag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/numericpropertytag'>;
}
declare module 'jsdoc/test/fixtures/objectkeys.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/objectkeys'>;
}
declare module 'jsdoc/test/fixtures/objectlit.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/objectlit'>;
}
declare module 'jsdoc/test/fixtures/objectlit2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/objectlit2'>;
}
declare module 'jsdoc/test/fixtures/objectlit3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/objectlit3'>;
}
declare module 'jsdoc/test/fixtures/objectpropertykeys.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/objectpropertykeys'>;
}
declare module 'jsdoc/test/fixtures/overridetag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/overridetag'>;
}
declare module 'jsdoc/test/fixtures/paramtag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/paramtag'>;
}
declare module 'jsdoc/test/fixtures/paramtag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/paramtag2'>;
}
declare module 'jsdoc/test/fixtures/paramtaginvalidtype.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/paramtaginvalidtype'>;
}
declare module 'jsdoc/test/fixtures/plugins.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/plugins'>;
}
declare module 'jsdoc/test/fixtures/privatetag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/privatetag'>;
}
declare module 'jsdoc/test/fixtures/privatetag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/privatetag2'>;
}
declare module 'jsdoc/test/fixtures/projecttag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/projecttag'>;
}
declare module 'jsdoc/test/fixtures/propertytag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/propertytag'>;
}
declare module 'jsdoc/test/fixtures/protectedtag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/protectedtag'>;
}
declare module 'jsdoc/test/fixtures/protectedtag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/protectedtag2'>;
}
declare module 'jsdoc/test/fixtures/quotename.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/quotename'>;
}
declare module 'jsdoc/test/fixtures/quotename2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/quotename2'>;
}
declare module 'jsdoc/test/fixtures/readonlytag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/readonlytag'>;
}
declare module 'jsdoc/test/fixtures/requirestag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/requirestag'>;
}
declare module 'jsdoc/test/fixtures/restparams.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/restparams'>;
}
declare module 'jsdoc/test/fixtures/restparams2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/restparams2'>;
}
declare module 'jsdoc/test/fixtures/returnstag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/returnstag'>;
}
declare module 'jsdoc/test/fixtures/scopetags.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/scopetags'>;
}
declare module 'jsdoc/test/fixtures/seetag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/seetag'>;
}
declare module 'jsdoc/test/fixtures/sincetag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/sincetag'>;
}
declare module 'jsdoc/test/fixtures/specialchars.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/specialchars'>;
}
declare module 'jsdoc/test/fixtures/specialnames.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/specialnames'>;
}
declare module 'jsdoc/test/fixtures/src/_dir2/four.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/src/_dir2/four'>;
}
declare module 'jsdoc/test/fixtures/src/_ignored.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/src/_ignored'>;
}
declare module 'jsdoc/test/fixtures/src/dir1/three.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/src/dir1/three'>;
}
declare module 'jsdoc/test/fixtures/src/one.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/src/one'>;
}
declare module 'jsdoc/test/fixtures/src/two.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/src/two'>;
}
declare module 'jsdoc/test/fixtures/starbangstar.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/starbangstar'>;
}
declare module 'jsdoc/test/fixtures/summarytag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/summarytag'>;
}
declare module 'jsdoc/test/fixtures/testPlugin1.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/testPlugin1'>;
}
declare module 'jsdoc/test/fixtures/testPlugin2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/testPlugin2'>;
}
declare module 'jsdoc/test/fixtures/this-and-objectlit.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/this-and-objectlit'>;
}
declare module 'jsdoc/test/fixtures/this.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/this'>;
}
declare module 'jsdoc/test/fixtures/this2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/this2'>;
}
declare module 'jsdoc/test/fixtures/this3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/this3'>;
}
declare module 'jsdoc/test/fixtures/this4.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/this4'>;
}
declare module 'jsdoc/test/fixtures/this5.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/this5'>;
}
declare module 'jsdoc/test/fixtures/thistag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/thistag'>;
}
declare module 'jsdoc/test/fixtures/todotag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/todotag'>;
}
declare module 'jsdoc/test/fixtures/tutorialtag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/tutorialtag'>;
}
declare module 'jsdoc/test/fixtures/typedeftag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/typedeftag'>;
}
declare module 'jsdoc/test/fixtures/typekind.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/typekind'>;
}
declare module 'jsdoc/test/fixtures/typetag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/typetag'>;
}
declare module 'jsdoc/test/fixtures/typetag2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/typetag2'>;
}
declare module 'jsdoc/test/fixtures/typetaginline.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/typetaginline'>;
}
declare module 'jsdoc/test/fixtures/typetagwithnewline.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/typetagwithnewline'>;
}
declare module 'jsdoc/test/fixtures/undocumentedtag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/undocumentedtag'>;
}
declare module 'jsdoc/test/fixtures/utf8.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/utf8'>;
}
declare module 'jsdoc/test/fixtures/var.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/var'>;
}
declare module 'jsdoc/test/fixtures/variations.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/variations'>;
}
declare module 'jsdoc/test/fixtures/variationtag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/variationtag'>;
}
declare module 'jsdoc/test/fixtures/versiontag.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/versiontag'>;
}
declare module 'jsdoc/test/fixtures/virtual.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/virtual'>;
}
declare module 'jsdoc/test/fixtures/virtual2.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/virtual2'>;
}
declare module 'jsdoc/test/fixtures/virtual3.js' {
  declare module.exports: $Exports<'jsdoc/test/fixtures/virtual3'>;
}
declare module 'jsdoc/test/jasmine-jsdoc.js' {
  declare module.exports: $Exports<'jsdoc/test/jasmine-jsdoc'>;
}
declare module 'jsdoc/test/lib/jasmine.js' {
  declare module.exports: $Exports<'jsdoc/test/lib/jasmine'>;
}
declare module 'jsdoc/test/reporter.js' {
  declare module.exports: $Exports<'jsdoc/test/reporter'>;
}
declare module 'jsdoc/test/runner.js' {
  declare module.exports: $Exports<'jsdoc/test/runner'>;
}
declare module 'jsdoc/test/spec-collection.js' {
  declare module.exports: $Exports<'jsdoc/test/spec-collection'>;
}
declare module 'jsdoc/test/specs/documentation/alias.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/alias'>;
}
declare module 'jsdoc/test/specs/documentation/also.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/also'>;
}
declare module 'jsdoc/test/specs/documentation/anonymousclass.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/anonymousclass'>;
}
declare module 'jsdoc/test/specs/documentation/arrowfunction.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/arrowfunction'>;
}
declare module 'jsdoc/test/specs/documentation/callback.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/callback'>;
}
declare module 'jsdoc/test/specs/documentation/classwithoutname.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/classwithoutname'>;
}
declare module 'jsdoc/test/specs/documentation/const.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/const'>;
}
declare module 'jsdoc/test/specs/documentation/defaultparams.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/defaultparams'>;
}
declare module 'jsdoc/test/specs/documentation/emptycomments.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/emptycomments'>;
}
declare module 'jsdoc/test/specs/documentation/exportclass.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/exportclass'>;
}
declare module 'jsdoc/test/specs/documentation/exportdefault.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/exportdefault'>;
}
declare module 'jsdoc/test/specs/documentation/exportdefaultclass.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/exportdefaultclass'>;
}
declare module 'jsdoc/test/specs/documentation/exports.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/exports'>;
}
declare module 'jsdoc/test/specs/documentation/funcExpression.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/funcExpression'>;
}
declare module 'jsdoc/test/specs/documentation/getset.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/getset'>;
}
declare module 'jsdoc/test/specs/documentation/inlinecomment.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/inlinecomment'>;
}
declare module 'jsdoc/test/specs/documentation/inlineparamcomment.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/inlineparamcomment'>;
}
declare module 'jsdoc/test/specs/documentation/inner.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/inner'>;
}
declare module 'jsdoc/test/specs/documentation/innerscope.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/innerscope'>;
}
declare module 'jsdoc/test/specs/documentation/instanceproperty.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/instanceproperty'>;
}
declare module 'jsdoc/test/specs/documentation/jsx.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/jsx'>;
}
declare module 'jsdoc/test/specs/documentation/lends.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/lends'>;
}
declare module 'jsdoc/test/specs/documentation/letkeyword.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/letkeyword'>;
}
declare module 'jsdoc/test/specs/documentation/methoddefinition.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/methoddefinition'>;
}
declare module 'jsdoc/test/specs/documentation/mixins.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/mixins'>;
}
declare module 'jsdoc/test/specs/documentation/moduleinner.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/moduleinner'>;
}
declare module 'jsdoc/test/specs/documentation/moduleisconstructor.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/moduleisconstructor'>;
}
declare module 'jsdoc/test/specs/documentation/moduleisfunction.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/moduleisfunction'>;
}
declare module 'jsdoc/test/specs/documentation/modules.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/modules'>;
}
declare module 'jsdoc/test/specs/documentation/objectkeys.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/objectkeys'>;
}
declare module 'jsdoc/test/specs/documentation/objectlit.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/objectlit'>;
}
declare module 'jsdoc/test/specs/documentation/objectpropertykeys.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/objectpropertykeys'>;
}
declare module 'jsdoc/test/specs/documentation/quotename.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/quotename'>;
}
declare module 'jsdoc/test/specs/documentation/restparams.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/restparams'>;
}
declare module 'jsdoc/test/specs/documentation/specialchars.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/specialchars'>;
}
declare module 'jsdoc/test/specs/documentation/specialnames.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/specialnames'>;
}
declare module 'jsdoc/test/specs/documentation/starbangstar.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/starbangstar'>;
}
declare module 'jsdoc/test/specs/documentation/this.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/this'>;
}
declare module 'jsdoc/test/specs/documentation/typetaginline.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/typetaginline'>;
}
declare module 'jsdoc/test/specs/documentation/typetagwithnewline.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/typetagwithnewline'>;
}
declare module 'jsdoc/test/specs/documentation/var.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/var'>;
}
declare module 'jsdoc/test/specs/documentation/variations.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/variations'>;
}
declare module 'jsdoc/test/specs/documentation/virtual.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/documentation/virtual'>;
}
declare module 'jsdoc/test/specs/jsdoc/augment.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/augment'>;
}
declare module 'jsdoc/test/specs/jsdoc/borrow.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/borrow'>;
}
declare module 'jsdoc/test/specs/jsdoc/config.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/config'>;
}
declare module 'jsdoc/test/specs/jsdoc/doclet.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/doclet'>;
}
declare module 'jsdoc/test/specs/jsdoc/name.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/name'>;
}
declare module 'jsdoc/test/specs/jsdoc/opts/argparser.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/opts/argparser'>;
}
declare module 'jsdoc/test/specs/jsdoc/opts/args.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/opts/args'>;
}
declare module 'jsdoc/test/specs/jsdoc/package.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/package'>;
}
declare module 'jsdoc/test/specs/jsdoc/path.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/path'>;
}
declare module 'jsdoc/test/specs/jsdoc/plugins.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/plugins'>;
}
declare module 'jsdoc/test/specs/jsdoc/readme.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/readme'>;
}
declare module 'jsdoc/test/specs/jsdoc/schema.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/schema'>;
}
declare module 'jsdoc/test/specs/jsdoc/src/astbuilder.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/src/astbuilder'>;
}
declare module 'jsdoc/test/specs/jsdoc/src/astnode.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/src/astnode'>;
}
declare module 'jsdoc/test/specs/jsdoc/src/filter.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/src/filter'>;
}
declare module 'jsdoc/test/specs/jsdoc/src/handlers.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/src/handlers'>;
}
declare module 'jsdoc/test/specs/jsdoc/src/parser.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/src/parser'>;
}
declare module 'jsdoc/test/specs/jsdoc/src/scanner.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/src/scanner'>;
}
declare module 'jsdoc/test/specs/jsdoc/src/syntax.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/src/syntax'>;
}
declare module 'jsdoc/test/specs/jsdoc/src/visitor.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/src/visitor'>;
}
declare module 'jsdoc/test/specs/jsdoc/src/walker.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/src/walker'>;
}
declare module 'jsdoc/test/specs/jsdoc/tag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/tag'>;
}
declare module 'jsdoc/test/specs/jsdoc/tag/dictionary.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/tag/dictionary'>;
}
declare module 'jsdoc/test/specs/jsdoc/tag/dictionary/definitions.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/tag/dictionary/definitions'>;
}
declare module 'jsdoc/test/specs/jsdoc/tag/inline.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/tag/inline'>;
}
declare module 'jsdoc/test/specs/jsdoc/tag/type.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/tag/type'>;
}
declare module 'jsdoc/test/specs/jsdoc/tag/validator.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/tag/validator'>;
}
declare module 'jsdoc/test/specs/jsdoc/template.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/template'>;
}
declare module 'jsdoc/test/specs/jsdoc/tutorial.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/tutorial'>;
}
declare module 'jsdoc/test/specs/jsdoc/tutorial/resolver.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/tutorial/resolver'>;
}
declare module 'jsdoc/test/specs/jsdoc/util/cast.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/util/cast'>;
}
declare module 'jsdoc/test/specs/jsdoc/util/doop.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/util/doop'>;
}
declare module 'jsdoc/test/specs/jsdoc/util/dumper.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/util/dumper'>;
}
declare module 'jsdoc/test/specs/jsdoc/util/error.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/util/error'>;
}
declare module 'jsdoc/test/specs/jsdoc/util/logger.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/util/logger'>;
}
declare module 'jsdoc/test/specs/jsdoc/util/markdown.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/util/markdown'>;
}
declare module 'jsdoc/test/specs/jsdoc/util/runtime.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/util/runtime'>;
}
declare module 'jsdoc/test/specs/jsdoc/util/templateHelper.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/jsdoc/util/templateHelper'>;
}
declare module 'jsdoc/test/specs/plugins/plugins.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/plugins/plugins'>;
}
declare module 'jsdoc/test/specs/tags/abstracttag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/abstracttag'>;
}
declare module 'jsdoc/test/specs/tags/accesstag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/accesstag'>;
}
declare module 'jsdoc/test/specs/tags/aliastag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/aliastag'>;
}
declare module 'jsdoc/test/specs/tags/augmentstag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/augmentstag'>;
}
declare module 'jsdoc/test/specs/tags/authortag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/authortag'>;
}
declare module 'jsdoc/test/specs/tags/borrowstag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/borrowstag'>;
}
declare module 'jsdoc/test/specs/tags/classdesctag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/classdesctag'>;
}
declare module 'jsdoc/test/specs/tags/classtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/classtag'>;
}
declare module 'jsdoc/test/specs/tags/constanttag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/constanttag'>;
}
declare module 'jsdoc/test/specs/tags/constructortag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/constructortag'>;
}
declare module 'jsdoc/test/specs/tags/constructstag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/constructstag'>;
}
declare module 'jsdoc/test/specs/tags/copyrighttag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/copyrighttag'>;
}
declare module 'jsdoc/test/specs/tags/defaulttag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/defaulttag'>;
}
declare module 'jsdoc/test/specs/tags/deprecatedtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/deprecatedtag'>;
}
declare module 'jsdoc/test/specs/tags/descriptiontag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/descriptiontag'>;
}
declare module 'jsdoc/test/specs/tags/enumtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/enumtag'>;
}
declare module 'jsdoc/test/specs/tags/eventfirestag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/eventfirestag'>;
}
declare module 'jsdoc/test/specs/tags/exampletag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/exampletag'>;
}
declare module 'jsdoc/test/specs/tags/exceptiontag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/exceptiontag'>;
}
declare module 'jsdoc/test/specs/tags/exportstag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/exportstag'>;
}
declare module 'jsdoc/test/specs/tags/externaltag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/externaltag'>;
}
declare module 'jsdoc/test/specs/tags/functiontag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/functiontag'>;
}
declare module 'jsdoc/test/specs/tags/globaltag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/globaltag'>;
}
declare module 'jsdoc/test/specs/tags/ignoretag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/ignoretag'>;
}
declare module 'jsdoc/test/specs/tags/implementstag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/implementstag'>;
}
declare module 'jsdoc/test/specs/tags/inheritdoctag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/inheritdoctag'>;
}
declare module 'jsdoc/test/specs/tags/interfacetag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/interfacetag'>;
}
declare module 'jsdoc/test/specs/tags/kindtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/kindtag'>;
}
declare module 'jsdoc/test/specs/tags/lendstag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/lendstag'>;
}
declare module 'jsdoc/test/specs/tags/licensetag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/licensetag'>;
}
declare module 'jsdoc/test/specs/tags/listenstag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/listenstag'>;
}
declare module 'jsdoc/test/specs/tags/memberoftag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/memberoftag'>;
}
declare module 'jsdoc/test/specs/tags/membertag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/membertag'>;
}
declare module 'jsdoc/test/specs/tags/mixestag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/mixestag'>;
}
declare module 'jsdoc/test/specs/tags/mixintag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/mixintag'>;
}
declare module 'jsdoc/test/specs/tags/moduletag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/moduletag'>;
}
declare module 'jsdoc/test/specs/tags/namespacetag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/namespacetag'>;
}
declare module 'jsdoc/test/specs/tags/nametag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/nametag'>;
}
declare module 'jsdoc/test/specs/tags/overridetag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/overridetag'>;
}
declare module 'jsdoc/test/specs/tags/overviewtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/overviewtag'>;
}
declare module 'jsdoc/test/specs/tags/paramtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/paramtag'>;
}
declare module 'jsdoc/test/specs/tags/privatetag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/privatetag'>;
}
declare module 'jsdoc/test/specs/tags/propertytag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/propertytag'>;
}
declare module 'jsdoc/test/specs/tags/protectedtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/protectedtag'>;
}
declare module 'jsdoc/test/specs/tags/readonlytag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/readonlytag'>;
}
declare module 'jsdoc/test/specs/tags/requirestag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/requirestag'>;
}
declare module 'jsdoc/test/specs/tags/returnstag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/returnstag'>;
}
declare module 'jsdoc/test/specs/tags/scopetags.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/scopetags'>;
}
declare module 'jsdoc/test/specs/tags/seetag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/seetag'>;
}
declare module 'jsdoc/test/specs/tags/sincetag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/sincetag'>;
}
declare module 'jsdoc/test/specs/tags/summarytag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/summarytag'>;
}
declare module 'jsdoc/test/specs/tags/thistag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/thistag'>;
}
declare module 'jsdoc/test/specs/tags/todotag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/todotag'>;
}
declare module 'jsdoc/test/specs/tags/tutorialtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/tutorialtag'>;
}
declare module 'jsdoc/test/specs/tags/typedeftag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/typedeftag'>;
}
declare module 'jsdoc/test/specs/tags/typekind.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/typekind'>;
}
declare module 'jsdoc/test/specs/tags/typetag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/typetag'>;
}
declare module 'jsdoc/test/specs/tags/undocumentedtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/undocumentedtag'>;
}
declare module 'jsdoc/test/specs/tags/variationtag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/variationtag'>;
}
declare module 'jsdoc/test/specs/tags/versiontag.js' {
  declare module.exports: $Exports<'jsdoc/test/specs/tags/versiontag'>;
}
declare module 'jsdoc/test/tutorials/src/x.js' {
  declare module.exports: $Exports<'jsdoc/test/tutorials/src/x'>;
}
