// flow-typed signature: 1fa6609f6eaf57968ac53ea18409f953
// flow-typed version: <<STUB>>/react-redux_v>=3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux/dist/react-redux' {
  declare module.exports: any;
}

declare module 'react-redux/dist/react-redux.min' {
  declare module.exports: any;
}

declare module 'react-redux/lib/components/connect' {
  declare module.exports: any;
}

declare module 'react-redux/lib/components/Provider' {
  declare module.exports: any;
}

declare module 'react-redux/lib/index' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/storeShape' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/warning' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/wrapActionCreators' {
  declare module.exports: any;
}

declare module 'react-redux/src/components/connect' {
  declare module.exports: any;
}

declare module 'react-redux/src/components/Provider' {
  declare module.exports: any;
}

declare module 'react-redux/src/index' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/storeShape' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/warning' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/wrapActionCreators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux/dist/react-redux.js' {
  declare module.exports: $Exports<'react-redux/dist/react-redux'>;
}
declare module 'react-redux/dist/react-redux.min.js' {
  declare module.exports: $Exports<'react-redux/dist/react-redux.min'>;
}
declare module 'react-redux/lib/components/connect.js' {
  declare module.exports: $Exports<'react-redux/lib/components/connect'>;
}
declare module 'react-redux/lib/components/Provider.js' {
  declare module.exports: $Exports<'react-redux/lib/components/Provider'>;
}
declare module 'react-redux/lib/index.js' {
  declare module.exports: $Exports<'react-redux/lib/index'>;
}
declare module 'react-redux/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/shallowEqual'>;
}
declare module 'react-redux/lib/utils/storeShape.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/storeShape'>;
}
declare module 'react-redux/lib/utils/warning.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/warning'>;
}
declare module 'react-redux/lib/utils/wrapActionCreators.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/wrapActionCreators'>;
}
declare module 'react-redux/src/components/connect.js' {
  declare module.exports: $Exports<'react-redux/src/components/connect'>;
}
declare module 'react-redux/src/components/Provider.js' {
  declare module.exports: $Exports<'react-redux/src/components/Provider'>;
}
declare module 'react-redux/src/index.js' {
  declare module.exports: $Exports<'react-redux/src/index'>;
}
declare module 'react-redux/src/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-redux/src/utils/shallowEqual'>;
}
declare module 'react-redux/src/utils/storeShape.js' {
  declare module.exports: $Exports<'react-redux/src/utils/storeShape'>;
}
declare module 'react-redux/src/utils/warning.js' {
  declare module.exports: $Exports<'react-redux/src/utils/warning'>;
}
declare module 'react-redux/src/utils/wrapActionCreators.js' {
  declare module.exports: $Exports<'react-redux/src/utils/wrapActionCreators'>;
}
