// flow-typed signature: 70f8099c896120a6e0625971ac1532e7
// flow-typed version: <<STUB>>/seamless-immutable_v^7.1.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'seamless-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'seamless-immutable' {
  declare module.exports: any;
}

// sources: https://github.com/rtfeldman/seamless-immutable/issues/121
// ->
// https://github.com/ajhyndman/fantasia/blob/master/flow/libs/seamless-immutable.d.js
//
//
declare module 'seamless-immutable' {
  declare type ImmutableType<T: Object | Array<*>> = T & {
    // Array methods
    flatMap(fn: Function): Array<any>;
    asObject(fn: Function): Object;
    asMutable(): Array<any>;
    // Object methods
    merge(collection: Array<any> | Object, deep?: Object): Object;
    set(key: string, value: any): Object;
    setIn(keyPath: Array<string>, value: any): Object;
    update(key: string, fn: Function): Object;
    updateIn(keyPath: Array<string>, fn: Function): Object;
    without(fn: Function): Object;
    without(keys: Array<string>): Object;
    without(...keys: Array<string>): Object;
    asMutable(): Array<any> | Object;
  };

  declare function from<T: Object | Array<*>> (spec: T): ImmutableType<T>;
  declare function isImmutable(x: *): boolean;

  declare export default function Immutable<T>(input: T): ImmutableType<T>;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'seamless-immutable/seamless-immutable.development' {
  declare module.exports: any;
}

declare module 'seamless-immutable/seamless-immutable.development.min' {
  declare module.exports: any;
}

declare module 'seamless-immutable/seamless-immutable.production.min' {
  declare module.exports: any;
}

declare module 'seamless-immutable/src/seamless-immutable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'seamless-immutable/seamless-immutable.development.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.development'>;
}
declare module 'seamless-immutable/seamless-immutable.development.min.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.development.min'>;
}
declare module 'seamless-immutable/seamless-immutable.production.min.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.production.min'>;
}
declare module 'seamless-immutable/src/seamless-immutable.js' {
  declare module.exports: $Exports<'seamless-immutable/src/seamless-immutable'>;
}
