// flow-typed signature: 2d61e0a5564b421c08d3c9f28fe2c8a4
// flow-typed version: <<STUB>>/tmp_v0.0.28/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tmp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tmp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tmp/Gruntfile' {
  declare module.exports: any;
}

declare module 'tmp/lib/tmp' {
  declare module.exports: any;
}

declare module 'tmp/test/base' {
  declare module.exports: any;
}

declare module 'tmp/test/dir-sync-test' {
  declare module.exports: any;
}

declare module 'tmp/test/dir-test' {
  declare module.exports: any;
}

declare module 'tmp/test/file-sync-test' {
  declare module.exports: any;
}

declare module 'tmp/test/file-test' {
  declare module.exports: any;
}

declare module 'tmp/test/graceful-sync' {
  declare module.exports: any;
}

declare module 'tmp/test/graceful' {
  declare module.exports: any;
}

declare module 'tmp/test/issue62-sync' {
  declare module.exports: any;
}

declare module 'tmp/test/issue62' {
  declare module.exports: any;
}

declare module 'tmp/test/keep-sync' {
  declare module.exports: any;
}

declare module 'tmp/test/keep' {
  declare module.exports: any;
}

declare module 'tmp/test/name-test' {
  declare module.exports: any;
}

declare module 'tmp/test/spawn-sync' {
  declare module.exports: any;
}

declare module 'tmp/test/spawn' {
  declare module.exports: any;
}

declare module 'tmp/test/symlinkme/file' {
  declare module.exports: any;
}

declare module 'tmp/test/unsafe-sync' {
  declare module.exports: any;
}

declare module 'tmp/test/unsafe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tmp/Gruntfile.js' {
  declare module.exports: $Exports<'tmp/Gruntfile'>;
}
declare module 'tmp/lib/tmp.js' {
  declare module.exports: $Exports<'tmp/lib/tmp'>;
}
declare module 'tmp/test/base.js' {
  declare module.exports: $Exports<'tmp/test/base'>;
}
declare module 'tmp/test/dir-sync-test.js' {
  declare module.exports: $Exports<'tmp/test/dir-sync-test'>;
}
declare module 'tmp/test/dir-test.js' {
  declare module.exports: $Exports<'tmp/test/dir-test'>;
}
declare module 'tmp/test/file-sync-test.js' {
  declare module.exports: $Exports<'tmp/test/file-sync-test'>;
}
declare module 'tmp/test/file-test.js' {
  declare module.exports: $Exports<'tmp/test/file-test'>;
}
declare module 'tmp/test/graceful-sync.js' {
  declare module.exports: $Exports<'tmp/test/graceful-sync'>;
}
declare module 'tmp/test/graceful.js' {
  declare module.exports: $Exports<'tmp/test/graceful'>;
}
declare module 'tmp/test/issue62-sync.js' {
  declare module.exports: $Exports<'tmp/test/issue62-sync'>;
}
declare module 'tmp/test/issue62.js' {
  declare module.exports: $Exports<'tmp/test/issue62'>;
}
declare module 'tmp/test/keep-sync.js' {
  declare module.exports: $Exports<'tmp/test/keep-sync'>;
}
declare module 'tmp/test/keep.js' {
  declare module.exports: $Exports<'tmp/test/keep'>;
}
declare module 'tmp/test/name-test.js' {
  declare module.exports: $Exports<'tmp/test/name-test'>;
}
declare module 'tmp/test/spawn-sync.js' {
  declare module.exports: $Exports<'tmp/test/spawn-sync'>;
}
declare module 'tmp/test/spawn.js' {
  declare module.exports: $Exports<'tmp/test/spawn'>;
}
declare module 'tmp/test/symlinkme/file.js' {
  declare module.exports: $Exports<'tmp/test/symlinkme/file'>;
}
declare module 'tmp/test/unsafe-sync.js' {
  declare module.exports: $Exports<'tmp/test/unsafe-sync'>;
}
declare module 'tmp/test/unsafe.js' {
  declare module.exports: $Exports<'tmp/test/unsafe'>;
}
