version: 2
jobs:
  build-node8:
    docker:
      - image: node:8
    working_directory: ~/w
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libelf1
      - run: npm i -g yarn
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn eslint
      - run: yarn flow
      - run: yarn coverage
      - run: yarn build
      - deploy:
          name: publish to npmjs.com
          command: scripts/publish
  build-node6:
    docker:
      - image: node:6
    working_directory: ~/w
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libelf1
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn eslint
      - run: yarn flow
      - run: yarn coverage
      - run: yarn build

workflows:
  version: 2
  build:
    jobs:
      - build-node8:
          requires:
            - build-node6
      - build-node6
